/** Keep in sync with `scripts/prerender-routes.mjs`. */
export const prerenderRoutes = [
  '/',
  '/docs',
  '/docs/motivation',
  '/docs/architektur',
  '/docs/service-schluessel',
  '/docs/backup-und-upgrade',
  '/docs/modelle',
  '/docs/kubernetes',
  '/docs/vergleiche/methodik',
  '/docs/vergleiche/paperless-ngx',
  '/docs/vergleiche/papra',
  '/docs/vergleiche/docspell',
  '/docs/vergleiche/mayan-edms',
  '/docs/vergleiche/docuware',
  '/docs/api',
  '/docs/sdks',
  '/impressum',
  '/datenschutz',
  '/en',
  '/en/docs',
  '/en/docs/motivation',
  '/en/docs/architecture',
  '/en/docs/service-api-keys',
  '/en/docs/backup-and-upgrade',
  '/en/docs/models',
  '/en/docs/kubernetes',
  '/en/docs/comparisons/methodology',
  '/en/docs/comparisons/paperless-ngx',
  '/en/docs/comparisons/papra',
  '/en/docs/comparisons/docspell',
  '/en/docs/comparisons/mayan-edms',
  '/en/docs/comparisons/docuware',
  '/en/docs/api',
  '/en/docs/sdks',
  '/en/impressum',
  '/en/datenschutz',
] as const;

export type PrerenderRoute = (typeof prerenderRoutes)[number];
