cla:
  path: CLA.md
  message: |
    Thank you for contributing to Docuvate. Please read [CLA.md](https://github.com/Docuvate/docuvate/blob/main/CLA.md) and sign the Contributor License Agreement so we can accept your pull request.
  allowlist:
    - tafaust
