apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - networkpolicy-external-egress.yaml
  - networkpolicy-migrate-external-egress.yaml
components:
  - ../../components/valkey
patches:
  - path: patch-replicas.yaml
  - path: patch-config-external.yaml
  - path: patch-ingress-host.yaml
  - path: patch-worker-resources.yaml
  - path: patch-networkpolicy-web.yaml
