apiVersion: v1
kind: ConfigMap
metadata:
  name: docuvate-config
data:
  MINIO_ENDPOINT: REPLACE_WITH_S3_ENDPOINT
  MINIO_PORT: "443"
  MINIO_USE_SSL: "true"
  MINIO_REGION: REPLACE_WITH_S3_REGION
  PASSWORD_RESET_MAIL_MODE: smtp
  SMTP_URL: REPLACE_WITH_SMTP_URL
  DOCUVATE_PUBLIC_WEB_URL: https://app.docuvate.example.com
  DOCUVATE_PUBLIC_API_URL: https://app.docuvate.example.com/api
