apiVersion: apps/v1
kind: Deployment
metadata:
  name: docuvate-mailpit
  labels:
    app.kubernetes.io/name: docuvate-mailpit
    app.kubernetes.io/component: mailpit
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: docuvate-mailpit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: docuvate-mailpit
        app.kubernetes.io/component: mailpit
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mailpit
          image: axllent/mailpit:v1.31.4@sha256:b68349e3a014b90c5610bfb26b2ae36f3892d7b8cf25ee140c6c71c98d2fcf48
          ports:
            - name: smtp
              containerPort: 1025
            - name: ui
              containerPort: 8025
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
