apiVersion: v1
kind: Service
metadata:
  name: docuvate-mailpit
  labels:
    app.kubernetes.io/name: docuvate-mailpit
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: docuvate-mailpit
  ports:
    - name: smtp
      port: 1025
      targetPort: smtp
    - name: ui
      port: 8025
      targetPort: ui
