apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docuvate-sftp-ingest-data
  labels:
    app.kubernetes.io/name: docuvate-sftp-ingest
    app.kubernetes.io/component: sftp-ingest
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
