"""Independent expected reading-order token sequences for semantic Typst export tests.

Hand-written per fixture (synthetic PDF intent). Not derived from exporter flow
helpers. Order/coverage metrics compare compiled PDF text extraction to these
sequences.
"""

from __future__ import annotations

from tests.layout_ssim_catalog import LAYOUT_SSIM_FIXTURES

_BANNER = (
    "synthetic",
    "layout",
    "regression",
    "document",
    "with",
    "enough",
    "words",
    "to",
    "classify",
    "as",
    "born",
    "digital",
)

SEMANTIC_READING_ORDER_BY_FIXTURE: dict[str, tuple[str, ...]] = {
    "delivery_note_table": (
        *_BANNER,
        "item",
        "qty",
        "widget",
        "a",
        "2",
        "widget",
        "b",
        "1",
    ),
    "layout_regression_payroll": (
        *_BANNER,
        "synthetic",
        "electronic",
        "payroll",
        "certificate",
        "for",
        "tax",
        "year",
        "2025",
        "fictional",
        "employer",
        "no",
        "personal",
        "data",
        "employee",
        "id",
        "syn",
        "4711",
        "1",
        "reporting",
        "period",
        "01",
        "01",
        "31",
        "12",
        "3",
        "gross",
        "wages",
        "incl",
        "benefits",
        "48",
        "250",
        "00",
        "5",
        "income",
        "tax",
        "withheld",
        "9",
        "120",
        "00",
    ),
    "form_disclosure": (
        *_BANNER,
        "label",
        "value",
        "text",
    ),
    "form_disclosure_acroform": (
        *_BANNER,
        "disclosure",
        "field",
        "value",
        "text",
        "x",
        "agree",
    ),
    "two_column_words": (
        *_BANNER,
        "lefta",
        "leftb",
        "righta",
        "rightb",
    ),
    "three_column_words": (
        *_BANNER,
        "cola1",
        "cola2",
        "colb1",
        "colb2",
        "colc1",
        "colc2",
    ),
    "delivery_note_multipage": (
        *_BANNER,
        "item",
        "qty",
        "widget",
        "a",
        "2",
        "widget",
        "b",
        "1",
        *_BANNER,
        "page",
        "two",
        "continues",
        "the",
        "synthetic",
        "delivery",
        "note",
        "footer",
        "line",
        "on",
        "page",
        "two",
    ),
    "mixed_page_sizes": (
        *_BANNER,
        *_BANNER,
    ),
    "multipage_portrait_landscape_table": (
        *_BANNER,
        "item",
        "row",
        "on",
        "page",
        "one",
        "qty",
        *_BANNER,
        "row",
        "on",
        "landscape",
        "page",
        "two",
        "continued",
        "table",
    ),
    "landscape_table": (
        *_BANNER,
        "landscape",
        "row",
        "a",
        "landscape",
        "row",
        "b",
    ),
    "rotated_mediabox": (
        *_BANNER,
    ),
    "rotated_heading": (
        *_BANNER,
        "rotated",
    ),
    "mixed_standard_fonts": (
        *_BANNER,
        "serif",
        "heading",
        "times",
        "monospace",
        "line",
        "courier",
        "body",
        "serif",
        "continues",
        "here",
    ),
    "symbol_and_helvetica": (
        *_BANNER,
        "bullet",
        "list",
        "marker",
        "row",
        "regular",
        "helvetica",
        "body",
        "text",
        "continues",
    ),
    "times_tight_serif_scale_left": (
        *_BANNER,
        "sca",
        "leo",
        "sca",
        "rigi",
        "lnetoi",
        "sricgai",
        "glehot",
        "nstcai",
        "0rgix",
        "hgti",
        "0rgix",
        "hgti",
        "lynetozi",
        "s1rixcgai",
        "aglehbot",
        "yncstcdzai",
        "2ragix",
        "hgbti",
        "2ragix",
        "hgbti",
        "elynetfozi",
        "c3grixgdhi",
        "agehfbt",
        "yincjtdzi",
        "4gaxhb",
        "geyij",
        "hfzt",
        "geyij",
        "hfzt",
        "c5gxdh",
        "aefb",
        "yicjdz",
        "gahb",
        "ef",
        "icg",
        "jdh",
        "icg",
        "jdh",
        "ef",
        "ij",
        "gh",
        "ij",
    ),
    "times_tight_serif_scale_right": (
        *_BANNER,
        "ser",
        "ifs",
        "ser",
        "cal",
        "iefrsi",
        "scaelr",
        "gifhst",
        "esreri",
        "ccgah",
        "olt",
        "l",
        "ccgah",
        "olt",
        "l",
        "iaefrsai",
        "sccaeolrl",
        "bgifhsct",
        "bedsreaeri",
        "ccbgah",
        "oclt",
        "l",
        "ccbgah",
        "oclt",
        "ficefrgsai",
        "dchcaoeiljl",
        "bgfhgct",
        "dedraei",
        "chbocijl",
        "gfehgat",
        "dchoeijl",
        "bfgc",
        "fdae",
        "hbcij",
        "fg",
        "dheij",
        "fg",
        "hij",
    ),
    "embedded_subset_dejavu": (
        *_BANNER,
        "embedded",
        "dejavu",
        "subset",
        "for",
        "layout",
        "regression",
        "unknown",
        "font",
        "name",
        "in",
        "ir",
        "exercises",
        "font_map",
        "fallback",
    ),
    "german_umlaut_body": (
        *_BANNER,
        "m",
        "cid",
        "228",
        "rz",
        "cid",
        "214",
        "ffnung",
        "stra",
        "cid",
        "223",
        "e",
        "gr",
        "cid",
        "252",
        "cid",
        "223",
        "e",
        "aus",
        "m",
        "cid",
        "252",
        "nchen",
    ),
    "cyrillic_body": (
        *_BANNER,
        "синтетический",
        "счёт",
        "для",
        "проверки",
        "кириллицы",
    ),
    "greek_body": (
        *_BANNER,
        "συνθετικό",
        "τιμολόγιο",
        "για",
        "ελληνικά",
    ),
    "scanned_invisible_ocr": (
        *_BANNER,
        "invoice",
        "syn",
        "9001",
        "line",
        "item",
        "alpha",
        "line",
        "item",
        "beta",
    ),
    "scanned_rotated_90": (
        "second",
        "ocr",
        "line",
        "on",
        "rotated",
        "pagerotated",
        "scan",
        "label",
        *_BANNER,
    ),
}

RELIABLE_SEMANTIC_FIXTURE_IDS: frozenset[str] = frozenset(
    f.fixture_id for f in LAYOUT_SSIM_FIXTURES if f.expects_reliable
)


def expected_reading_order_tokens(fixture_id: str) -> list[str]:
    raw = SEMANTIC_READING_ORDER_BY_FIXTURE.get(fixture_id)
    if raw is None:
        raise KeyError(f"No semantic reading-order ground truth for fixture: {fixture_id}")
    return list(raw)


def interleaved_column_major_tokens(fixture_id: str) -> list[str] | None:
    """Deliberately wrong row-major interleaving for multi-column fixtures."""
    if fixture_id == "two_column_words":
        return [
            *_BANNER,
            "lefta",
            "righta",
            "leftb",
            "rightb",
        ]
    if fixture_id == "three_column_words":
        return [
            *_BANNER,
            "cola1",
            "colb1",
            "colc1",
            "cola2",
            "colb2",
            "colc2",
        ]
    return None


def assert_reliable_fixtures_have_ground_truth() -> None:
    missing = RELIABLE_SEMANTIC_FIXTURE_IDS - SEMANTIC_READING_ORDER_BY_FIXTURE.keys()
    assert not missing, f"Missing semantic ground truth for reliable fixtures: {sorted(missing)}"
