apiVersion: v1
kind: ServiceAccount
metadata:
  name: docuvate-api
  labels:
    app.kubernetes.io/name: docuvate-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: docuvate-web
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: docuvate-worker
automountServiceAccountToken: false
