apiVersion: apps/v1
kind: Deployment
metadata:
  name: docuvate-worker
spec:
  template:
    spec:
      nodeSelector:
        nvidia.com/gpu.present: "true"
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: worker
          image: docuvate-worker-gpu
          resources:
            limits:
              nvidia.com/gpu: 1
