apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - networkpolicy-api-external-egress.yaml
components:
  - ../../components/postgres
  - ../../components/valkey
  - ../../components/minio
patches:
  - path: patch-ingress-host.yaml
  - path: patch-homelab-config.yaml
  - path: patch-db-migrate-wait.yaml
