apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: docuvate
spec:
  rules:
    - host: docuvate.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docuvate-web
                port:
                  name: http
