apiVersion: v1
kind: Service
metadata:
  name: docuvate-worker
  labels:
    app.kubernetes.io/name: docuvate-worker
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: docuvate-worker
  ports:
    - name: http
      port: 8000
      targetPort: http
