apiVersion: v1
kind: Service
metadata:
  name: docuvate-postgres
  labels:
    app.kubernetes.io/name: docuvate-postgres
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: docuvate-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
