import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const tokensDir = path.join(__dirname, 'tokens');
const distCss = path.join(__dirname, 'dist/css');
const distJs = path.join(__dirname, 'dist/js');
const distDart = path.join(__dirname, 'dist/dart');

const PREFIX = 'dv';
const THEME_ATTR = 'data-docuvate-theme';

function readJson(name) {
  return JSON.parse(fs.readFileSync(path.join(tokensDir, name), 'utf8'));
}

function flattenThemeColors(themeId, colors) {
  const out = [];
  for (const [key, token] of Object.entries(colors)) {
    out.push({
      name: `color-${key}`,
      value: token.value,
      theme: themeId,
    });
  }
  return out;
}

function flattenObject(obj, prefixParts = []) {
  const out = [];
  for (const [key, val] of Object.entries(obj)) {
    const parts = [...prefixParts, key];
    if (val && typeof val === 'object' && 'value' in val) {
      out.push({ path: parts, value: val.value });
    } else if (val && typeof val === 'object') {
      out.push(...flattenObject(val, parts));
    }
  }
  return out;
}

function tokenPathToCssVar(pathParts) {
  return `--${PREFIX}-${pathParts.join('-')}`;
}

function tokenPathToCamel(pathParts) {
  const flat = pathParts.join('-').split('-').filter(Boolean);
  return flat.map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1))).join('');
}

function tokenPathToDartField(pathParts) {
  return pathParts.map((p) => p.replace(/-([a-z])/g, (_, c) => c.toUpperCase())).join('');
}

function buildThemedCss(colorJson) {
  const light = flattenThemeColors('light', colorJson.color.light);
  const dark = flattenThemeColors('dark', colorJson.color.dark);
  const lines = [
    '/** Generated by @docuvate/tokens — do not edit */',
    '',
    `:root, [${THEME_ATTR}='light'] {`,
  ];
  for (const t of light) {
    lines.push(`  ${tokenPathToCssVar(['color', t.name.replace(/^color-/, '')])}: ${t.value};`);
  }
  lines.push('}');
  lines.push('');
  lines.push(`[${THEME_ATTR}='dark'] {`);
  for (const t of dark) {
    lines.push(`  ${tokenPathToCssVar(['color', t.name.replace(/^color-/, '')])}: ${t.value};`);
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function buildStaticCss() {
  const chunks = [];
  for (const file of [
    'typography.json',
    'space.json',
    'radius.json',
    'shadow.json',
    'motion.json',
  ]) {
    const data = readJson(file);
    chunks.push(...flattenObject(data));
  }
  const lines = [`:root {`];
  for (const t of chunks) {
    lines.push(`  ${tokenPathToCssVar(t.path)}: ${t.value};`);
  }
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

function buildTs(colorJson) {
  const staticFlat = [];
  for (const file of [
    'typography.json',
    'space.json',
    'radius.json',
    'shadow.json',
    'motion.json',
  ]) {
    staticFlat.push(...flattenObject(readJson(file)));
  }
  const lines = [
    '/** Generated by @docuvate/tokens — do not edit */',
    '',
    'export const docuvateThemeAttribute = "data-docuvate-theme";',
    '',
    'export const tokens = {',
  ];
  for (const t of staticFlat) {
    const key = tokenPathToCamel(t.path);
    lines.push(`  ${key}: ${JSON.stringify(t.value)},`);
  }
  for (const theme of ['light', 'dark']) {
    lines.push(`  color${theme.charAt(0).toUpperCase() + theme.slice(1)}: {`);
    for (const [key, token] of Object.entries(colorJson.color[theme])) {
      lines.push(`    ${tokenPathToCamel(['color', key])}: ${JSON.stringify(token.value)},`);
    }
    lines.push('  },');
  }
  lines.push('};');
  lines.push('');
  lines.push(`export const labelDefaultColor = tokens.colorLight.colorLabelDefault;`);
  lines.push('');
  return lines.join('\n');
}

function buildTsDecl(colorJson) {
  const staticFlat = [];
  for (const file of [
    'typography.json',
    'space.json',
    'radius.json',
    'shadow.json',
    'motion.json',
  ]) {
    staticFlat.push(...flattenObject(readJson(file)));
  }
  const lines = [
    '/** Generated by @docuvate/tokens — do not edit */',
    '',
    'export declare const docuvateThemeAttribute: "data-docuvate-theme";',
    'export type DocuvateTheme = "light" | "dark";',
    '',
    'type ThemeColors = {',
  ];
  for (const key of Object.keys(colorJson.color.light)) {
    lines.push(`  ${tokenPathToCamel(['color', key])}: string;`);
  }
  lines.push('};');
  lines.push('');
  lines.push('export declare const tokens: {');
  for (const t of staticFlat) {
    lines.push(`  ${tokenPathToCamel(t.path)}: string;`);
  }
  for (const theme of ['light', 'dark']) {
    lines.push(`  color${theme.charAt(0).toUpperCase() + theme.slice(1)}: ThemeColors;`);
  }
  lines.push('};');
  lines.push('');
  lines.push('export declare const labelDefaultColor: string;');
  lines.push('');
  return lines.join('\n');
}

function hexToFlutterColor(hex) {
  const h = hex.replace('#', '');
  if (h.length === 6) {
    return `Color(0xFF${h.toUpperCase()})`;
  }
  return `Color(0xFF000000)`;
}

function buildDart(colorJson) {
  const staticFlat = [];
  for (const file of [
    'typography.json',
    'space.json',
    'radius.json',
    'shadow.json',
    'motion.json',
  ]) {
    staticFlat.push(...flattenObject(readJson(file)));
  }
  const lines = [
    '// Generated by @docuvate/tokens — do not edit',
    "import 'dart:ui' show Color;",
    '',
    'enum DocuvateThemeId { light, dark }',
    '',
    'class DocuvateTokens {',
    '  DocuvateTokens._();',
    '',
  ];
  for (const t of staticFlat) {
    const name = tokenPathToDartField(t.path);
    const isPx = String(t.value).endsWith('px');
    const isRem = String(t.value).endsWith('rem');
    if (isPx) {
      lines.push(`  static const double ${name} = ${parseFloat(t.value)};`);
    } else if (isRem) {
      lines.push(`  static const double ${name} = ${parseFloat(t.value)} * 16;`);
    } else {
      lines.push(`  static const String ${name} = ${JSON.stringify(t.value)};`);
    }
  }
  lines.push('');
  lines.push('  static Color color(DocuvateThemeId theme, String role) {');
  lines.push('    switch (theme) {');
  lines.push('      case DocuvateThemeId.light:');
  lines.push('        return _lightColor(role);');
  lines.push('      case DocuvateThemeId.dark:');
  lines.push('        return _darkColor(role);');
  lines.push('    }');
  lines.push('  }');
  lines.push('');
  for (const theme of ['light', 'dark']) {
    lines.push(`  static Color _${theme}Color(String role) {`);
    lines.push('    switch (role) {');
    for (const [key, token] of Object.entries(colorJson.color[theme])) {
      lines.push(`      case '${key}':`);
      lines.push(`        return ${hexToFlutterColor(token.value)};`);
    }
    lines.push('      default:');
    lines.push('        return const Color(0xFF000000);');
    lines.push('    }');
    lines.push('  }');
    lines.push('');
  }
  lines.push('}');
  lines.push('');
  lines.push('extension DocuvateThemeData on DocuvateThemeId {');
  lines.push("  Color bg() => DocuvateTokens.color(this, 'bg');");
  lines.push("  Color accent() => DocuvateTokens.color(this, 'accent');");
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

/** Style Dictionary pass validates token JSON shape. */
async function runStyleDictionaryValidate() {
  const sd = new StyleDictionary({
    log: { verbosity: 'silent' },
    source: [path.join(tokensDir, '**/*.json')],
    platforms: {
      json: {
        transformGroup: 'js',
        buildPath: path.join(__dirname, '.sd-cache/'),
        files: [
          {
            destination: 'tokens.raw.json',
            format: 'json/nested',
          },
        ],
      },
    },
  });
  await sd.buildAllPlatforms();
}

fs.mkdirSync(distCss, { recursive: true });
fs.mkdirSync(distJs, { recursive: true });
fs.mkdirSync(distDart, { recursive: true });

await runStyleDictionaryValidate();

const colorJson = readJson('color.json');
const css =
  buildThemedCss(colorJson) +
  buildStaticCss() +
  `@media (prefers-reduced-motion: reduce) {
  * {
    animation-duration: 0.01ms !important;
    transition-duration: 0.01ms !important;
  }
}
`;

fs.writeFileSync(path.join(distCss, 'tokens.css'), css);
fs.writeFileSync(path.join(distJs, 'tokens.js'), buildTs(colorJson));
fs.writeFileSync(path.join(distJs, 'tokens.d.ts'), buildTsDecl(colorJson));
fs.writeFileSync(path.join(distDart, 'docuvate_tokens.dart'), buildDart(colorJson));

console.log('Built @docuvate/tokens');
