// SPDX-FileCopyrightText: 2026 Thomas Faust
// SPDX-License-Identifier: LicenseRef-Docuvate-SUL-1.0

import {
  EMBEDDING_DENSITY_MIN_UNIQUE_DOCUMENTS_COARSE_READY,
  EMBEDDING_DENSITY_MIN_UNIQUE_DOCUMENTS_FINE_READY_PER_LABEL,
  EMBEDDING_DENSITY_READINESS_HINT_EN,
} from './embedding-density-constants.js';

/** @see EMBEDDING_DENSITY_READINESS_HINT_EN */
export const EMBEDDING_DENSITY_READINESS_HINT = EMBEDDING_DENSITY_READINESS_HINT_EN;

export {
  EMBEDDING_DENSITY_MIN_UNIQUE_DOCUMENTS_COARSE_READY,
  EMBEDDING_DENSITY_MIN_UNIQUE_DOCUMENTS_FINE_READY_PER_LABEL,
};

export const EMBEDDING_DENSITY_CALIBRATION_DEBOUNCE_MS = 120_000;

export const EMBEDDING_DENSITY_RECALIBRATION_SCAN_MS = 600_000;

/** New labeled blocks since last calibration run before scheduling a refresh. */
export const EMBEDDING_DENSITY_RECALIBRATION_MIN_NEW_EXAMPLES = 80;
