apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docuvate-homelab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Docuvate/docuvate.git
    targetRevision: main
    path: deploy/kustomize/overlays/homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: docuvate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
