{{- if and .Values.sftpIngest.enabled .Values.sftpIngest.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sftpIngest.existingSecret }}
type: Opaque
stringData:
  {{ .Values.sftpIngest.serviceApiKeySecretKey }}: REPLACE_WITH_SFTP_INGEST_SERVICE_KEY
{{- end }}
