{{- if .Values.sftpIngest.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: docuvate-sftp-ingest
spec:
  type: {{ if .Values.sftpIngest.exposeSftp }}NodePort{{ else }}ClusterIP{{ end }}
  selector:
    app.kubernetes.io/name: docuvate-sftp-ingest
  ports:
    - name: http
      port: 8080
      targetPort: http
    {{- if .Values.sftpIngest.exposeSftp }}
    - name: sftp
      port: 2222
      targetPort: sftp
      nodePort: {{ .Values.sftpIngest.sftpNodePort }}
    {{- end }}
{{- end }}
