/** Customer-facing URL paths (English). */
export const routes = {
  home: '/',
  login: '/login',
  loginTwoFactor: '/login/two-factor',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  inviteAccept: '/invite',
  inbox: '/inbox',
  documents: '/documents',
  savedViews: '/documents/views',
  document: (id: string) => `/documents/${id}`,
  filesystem: '/filesystem',
  filesystemContainer: (mappeId: string) => `/filesystem/containers/${mappeId}`,
  filesystemFolder: (folderId: string) => `/filesystem/folders/${folderId}`,
  structureLabels: '/structure/labels',
  structureRecognizedFields: '/structure/recognized-fields',
  settings: '/settings',
  settingsConnectors: '/settings/connectors',
  settingsPaperlessConnector: (installationId: string) =>
    `/settings/connectors/paperless/${installationId}`,
  settingsBlockedLabels: '/settings/blocked-labels',
  settingsAdmin: '/settings/admin',
  settingsAdminUsers: '/settings/admin/users',
  settingsAccountSecurity: '/settings/account-security',
  docsStyles: '/docs/styles',
  docsConnectorsOAuthSetup: '/docs/connectors/oauth-setup',
} as const;
